version: "2.0"
services:
    web:
        container_name: back-web
        image: docker-web:1.0
        restart: always
        ports:
          - "7001:5000"
          - "7002:9001"
        volumes:
          - ./volumes/docker-entrypoint.sh:/docker-entrypoint.sh
          - ./backup:/usr/src
          - ./volumes/supervisor:/etc/supervisor
          - ./volumes/nginx:/etc/nginx
        depends_on:
          - db


    db:
        container_name: back-db
        image: mysql:5.6
        restart: always
        ports:
          - "3306:3306"
        volumes:
          - ./volumes/mysql/conf.d:/etc/mysql/conf.d
          - ./volumes/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
          - ./db:/var/lib/mysql:rw
        environment:
          - MYSQL_DATABASE=backup
          - MYSQL_ROOT_PASSWORD=123456

