# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserKind',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户分类的id')),
                ('userKind', models.CharField(choices=[('T', '游客'), ('U', '用户')], default='T', max_length=50, verbose_name='用户的分类')),
            ],
            options={
                'db_table': 'UserKind',
            },
        ),
    ]
