# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkind',
            name='userKind',
            field=models.CharField(choices=[('T', '游客'), ('U', '用户')], default='T', max_length=5, verbose_name='用户的分类'),
        ),
    ]
