# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-31 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20180530_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='文件的ID')),
                ('title', models.CharField(max_length=50, verbose_name='文件的标题')),
                ('address', models.CharField(max_length=50, verbose_name='文件的地址')),
                ('size', models.IntegerField(verbose_name='文件的大小')),
                ('createTime', models.DateTimeField(verbose_name='文件初次上传的时间')),
                ('modifyTime', models.DateTimeField(verbose_name='文件修改的时间')),
                ('status', models.CharField(max_length=10, verbose_name='文件的状态,保留吧，暂时用不到')),
                ('belongKind', models.CharField(choices=[('music', '音频'), ('video', '视频'), ('document', '文档')], default='document', max_length=10, verbose_name='文件的类型')),
            ],
            options={
                'db_table': 'Resource',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户的id')),
                ('name', models.CharField(max_length=25, verbose_name='用户的姓名，汉字')),
                ('username', models.CharField(max_length=25, verbose_name='用户名')),
                ('password', models.CharField(max_length=15, verbose_name='用户的登录密码')),
                ('email', models.EmailField(max_length=254, verbose_name='用户的Email')),
                ('sex', models.CharField(choices=[('man', '男'), ('woman', '女')], default='man', max_length=5, verbose_name='用户的性别')),
                ('image', models.CharField(max_length=50, verbose_name='用户的头像地址')),
                ('status', models.CharField(choices=[('active', '正常'), ('freeze', '冻结')], default='active', max_length=15, verbose_name='用户的状态')),
                ('belongKind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.UserKind')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='belongUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.User'),
        ),
    ]
